### ISSUE TITLE
Umbenennen Configs von SMA auf SEPPmail

### ISSUE THREAD

**Issue by RStadlmair** [seppmail/SEPPmailAPI#11]
Wie besprochen . . .
Und SEPPmail bitte immer mit SEPP in groß

**Comment by RStadlmair** [comment]
Das ist schon gefixt oder ? - Sehe bei mir jetzt lokal den SecretStore "SEPPmail". Wenn ja dann mach es zu bitte

**Comment by hansh512** [comment]
Guten Morgen Roman,

mach ich. Ich habe zwar die Issue Nummer angegeben, hat aber scheinbar nicht automatisch geschlossen.

LG

Hans

Hans Halbmayr
Adersdorf 11/2
3354 Wolfsbach

UID-Nummer: ATU62751588

***@***.******@***.***>
+43 (0)699-819 65 519

**Comment by hansh512** [comment]
Prefix renamed to SEPPmail
