### ISSUE TITLE
Remove reference to Public\ModuleInit.ps1 from manifest

### ISSUE THREAD

**Issue by hansh512** [seppmail/SEPPmailAPI#14]
Bitte im Manifest bitte die Zeil 74 entfernen. Da wir das File
- Public\ModuleInit.ps1
gelöscht haben, lässt sich das Module nicht mehr laden (meine Mail mit Screenshot)
Danke!

**Comment by RStadlmair** [comment]
ich fixe das - Moment

**Comment by hansh512** [comment]
passt, ich pulle dann wieder

LG

Hans

Hans Halbmayr
Adersdorf 11/2
3354 Wolfsbach

UID-Nummer: ATU62751588

***@***.******@***.***>
+43 (0)699-819 65 519
