### ISSUE TITLE
Get-SMAConfig -List soll den config-Status ausgeben

### ISSUE THREAD

**Issue by RStadlmair** [seppmail/SEPPmailAPI#15]
Es ist nicht erkennbar welche die aktive Konfig ist.

Bei Get-SMAConfig -List sollen zusätzlich 2 Spalten ganz rechts auftauchen (Default und Active) bei denen mam sieht in welchem Status die Configs sind.

Ideen dazu ?

**Comment by hansh512** [comment]
Hallo Roman,

laut eurer Anforderung war

  *   aktive config, Get-SMAConfig ohne Parameter
  *   default config, Get-SMAConfig mit -Default
  *   alle Configs, Get-SMAConfig -List

Ist das dann nicht verwirrend?


LG

Hans

Hans Halbmayr
Adersdorf 11/2
3354 Wolfsbach

UID-Nummer: ATU62751588

***@***.******@***.***>
+43 (0)699-819 65 519

From: Roman Stadlmair ***@***.***>
Sent: Montag, 12. Juli 2021 09:35
To: seppmail/SEPPmailAPI ***@***.***>
Cc: Hans Halbmayr ***@***.***>; Assign ***@***.***>
Subject: [seppmail/SEPPmailAPI] Get-SMAConfig -List soll den config-Status ausgeben (#15)


Es ist nicht erkennbar welche die aktive Konfig ist.

Bei Get-SMAConfig -List sollen zusätzlich 2 Spalten ganz rechts auftauchen (Default und Active) bei denen mam sieht in welchem Status die Configs sind.

Ideen dazu ?

**Comment by RStadlmair** [comment]
Hmmm, dachte mir einfach wenn ich eine Liste von 10 Configs sehe, wäre spannend welche grade Aktiv bzw Default ist.

Regards/Roman Stadlmair
mobile: +43 676 43 16 002

**Comment by hansh512** [comment]
Was würdest du in die Spalte schreiben?

LG

Hans

Hans Halbmayr
Adersdorf 11/2
3354 Wolfsbach

UID-Nummer: ATU62751588

***@***.******@***.***>
+43 (0)699-819 65 519

**Comment by RStadlmair** [comment]
True und False, das sollte auch Teil des Objektes sein, dann kann man es auch in der Pipeline verwenden.

**Comment by hansh512** [comment]
Soll das NUR bei -List der Fall sein?

Assigned #15<https://github.com/seppmail/SEPPmailAPI/issues/15> to @hansh512<https://github.com/hansh512>.

**Comment by RStadlmair** [comment]
Hmm, hab ich auch nachgedacht.

Get-SMAConfig (ohne Parameter) zeigt die aktuelle aktive Konfig

Get-SMAConfig -SetDefault muss mit Namen verwendet werden, hier könnte es eventuell Sinn machen wenn man bei der Ausgabe sieht ob die grade aktiv ist.

Wenns einfacher zu implementieren ist dann gerne auch bei allen.
R.

**Comment by hansh512** [comment]
Updated Get-SMAConfiguration, added columns
