### ISSUE TITLE
Default configuration not used after init start

### ISSUE THREAD

**Issue by RStadlmair** [seppmail/SEPPmailAPI#18]
After loading the module in a new session i have the configurations still stored. But when i try to run test-smaconfiguration i am asked about the config i want to use (see below). It should use the "is Actve" configuration.
![grafik](https://user-images.githubusercontent.com/22378822/126031641-2e41333f-db29-4f86-9050-0c5fa0c1ba0d.png)

**Comment by hansh512** [comment]
The requirement was that the command tests a configuration.
In case of a troubleshooting process, it would be better to select the configuration to test.

From: Roman Stadlmair ***@***.***>
Sent: Samstag, 17. Juli 2021 10:47
To: seppmail/SEPPmailAPI ***@***.***>
Cc: Hans Halbmayr ***@***.***>; Assign ***@***.***>
Subject: [seppmail/SEPPmailAPI] Default configuration not used after init start (#18)


After loading the module in a new session i have the configurations still stored. But when i try to run test-smaconfiguration i am asked about the config i want to use (see below). It should use the "is Actve" configuration.
[Image removed by sender. grafik]<https://user-images.githubusercontent.com/22378822/126031641-2e41333f-db29-4f86-9050-0c5fa0c1ba0d.png>

**Comment by hansh512** [comment]
The requirement was that the command tests a configuration.
In case of a troubleshooting process, it would be better to select the configuration to test.
In my opinion this is not a bug.

**Comment by RStadlmair** [comment]
so true, all other CmdLets use the default config in a new session. Case closed.
