### ISSUE TITLE
$boundParam (Line  567) in Set-SMACustomer needed ?

### ISSUE THREAD

**Issue by RStadlmair** [seppmail/SEPPmailAPI#19]
VS-Code grumbles this is a non-used variable ..

**Comment by hansh512** [comment]
No un-used variable found (in my VS Code).
The only thing I have found is a SupportsShouldProcess in the test command.
From: Roman Stadlmair ***@***.***>
Sent: Samstag, 17. Juli 2021 11:43
To: seppmail/SEPPmailAPI ***@***.***>
Cc: Hans Halbmayr ***@***.***>; Assign ***@***.***>
Subject: [seppmail/SEPPmailAPI] $boundParam (Line 567) in Set-SMACustomer needed ? (#19)


VS-Code grumbles this is a non-used variable ..

**Comment by hansh512** [comment]
Could you please give me the name of the function.
Thanks

**Comment by RStadlmair** [comment]
(Line 567) in Set-SMACustomer

**Comment by hansh512** [comment]
I think you have defined the var $boundParam. You ref this var in function New-SMAQueryString.

**Comment by RStadlmair** [comment]
true, its for the varoius options to create a query string. Case closed
