### ISSUE TITLE
LicenseInfo / Statistics

### ISSUE THREAD

**Issue by marcohofbeck** [seppmail/SEPPmailAPI#30]
Hi, 

beim Abrufen der Statistiken über die REST-API "https://SYSTEM/v1/statistics" kommt leider bei jedem Benutzer bei "Registered User" nur eine 0. Somit kann man leider nicht filtern, welche Benutzer wirklich aktiv sind und welche inaktiv sind und gelöscht werden könnten. 

![License](https://user-images.githubusercontent.com/49472460/148742068-b4a8f699-5729-4c81-bc66-efdc5abd40a4.png)

Gibt es hierfür einen anderen Weg? 

Des Weiteren kommt beim Aufruf von Get-SMAEncInfo leider nur folgendes und somit kann dieser Befehl nicht wirklich genutzt werden. 

![EncInfo](https://user-images.githubusercontent.com/49472460/148742274-de639a61-bf2f-46e1-9556-f7ace25774de.png)

Danke für die Hilfe. 

Viele Grüße, 
Marco Hofbeck

**Comment by RStadlmair** [comment]
Hallo und sorry für die späte Antwort.

Bei Fragen und Problemen bitt immer E-mail an den SEPPmail Support schreiben.

Das erste Problem habe ich grade getestet.
Mit Find-SMAUser sieht man ob der User das gesetzt hat.

Zur EncInfo: Da die Ausgabe ist verbesserungswürdig. 
Wenn man allerdings ein Objekt draus erzeugt kann man reintauchen.

Beispiel:
```powershell
$EncInfo = Get-SMAEncInfo

$encInfo.smime
$encinfo.webmail
```

Man kann auch nach dem Punkt ($encinfo.) einfach TAB drücken, dann sieht man was möglich ist.
